env:
 - CI=false

language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage
  #- npm run build

after_script:
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
